### ISSUE TITLE
Bug when pressing Esc from Home screen

### ISSUE THREAD

**Issue by jaybirdjuju** [stianhoiland/cmdtab#1]
Hi there!

I loove this app and your work!!

The one issue I'm having is when I open cmdtab from Home screen and press Esc it jumps to one of my open windows/apps instead of closing down. This does not happen when I click outside the app to cancel. Only seems to happen from Home screen.

Also, some of your commit messages are hilarious :D cee0f50924bc6c76ff33afdf8263652885ded8cc 27dd7cbfe72de846bef6c57a63cb707bc9803390 and more...
Regards,
Your #1 Fangirl 
(Full disclosure, I'm his gf <3)

**Comment by stianhoiland** [comment]
Okay, fixed it now. Thanks for the feedback :* (Remember to download the updated version when it comes online.)
