### ISSUE TITLE
Crashes. Faulting module name: ucrtbase.dll

### ISSUE THREAD

**Issue by vzjrz** [stianhoiland/cmdtab#2]
Crashes as soon as I try alt+tab key combination.
Using version: cmdtab-v1.4-win-x86_64
Event viewer shows:
```
Faulting application name: cmdtab.exe, version: 0.0.0.0, time stamp: 0x6626d15d
Faulting module name: ucrtbase.dll, version: 10.0.19041.3636, time stamp: 0x81cf5d89
Exception code: 0xc0000409
Fault offset: 0x0000000000071208
Faulting process id: 0x3298
Faulting application start time: 0x01da9fb307b8622a
Faulting application path: C:\Data\Files\cmdtab-v1.4-win-x86_64\cmdtab.exe
Faulting module path: C:\WINDOWS\System32\ucrtbase.dll
```

**Comment by stianhoiland** [comment]
Interesting. Which version of Windows are you on?

**Comment by stianhoiland** [comment]
According to [this SO answer](https://stackoverflow.com/a/49781951/659310), it's a STATUS_STACK_BUFFER_OVERRUN. I'll look into it.

**Comment by vzjrz** [comment]
Windows info:
```
Edition	Windows 10 Pro
Version	22H2
Installed on	‎2022-‎02-‎19
OS build	19045.4291
Experience	Windows Feature Experience Pack 1000.19056.1000.0
```
I tried v1.3, v1.2 and they both crashed. But v1.1 did not.

**Comment by vzjrz** [comment]
Seems like a program I'm runnning called MediaMonkey is causing it to crash:

![proc](https://github.com/stianhoiland/cmdtab/assets/930620/054bfeb2-cea9-4e57-86a9-e77fbceca516)

**Comment by stianhoiland** [comment]
Ah, interesting. Nice investigation. To temporarily fix this issue, you can change line 298 from
`name.length = length;`
to
`name.length = length+1;`
and recompile. I downloaded MediaMonkey, and got the same crash, tried this fix, and it doesn't crash now.

I'll try to understand better why this occurs before I push an update. Thanks for your effort :)

**Comment by stianhoiland** [comment]
I didn't end up investigating this issue any further and just slapped on a `+1` as above. [This commit](https://github.com/stianhoiland/cmdtab/blob/47311a8d48058c803c1116718ed48b0fa0049a21/src/cmdtab.c#L425) should fix the issue. Make sure to download the upcoming v1.5 release when it drops.
