### ISSUE TITLE
Alt+` leaves Alt button pressed

### ISSUE THREAD

**Issue by harphere** [stianhoiland/cmdtab#4]
Hi, great work here.

When I cycle through Chrome using Alt+`, after stopping on the Chrome window I want and releasing the Alt button, the focus shifts to the 3 dot menu and I have to press Esc to remove the focus from the menu.

How can I avoid this?

**Comment by stianhoiland** [comment]
Does this seem to particularly affect Chrome, or other applications/windows as well?

**Comment by harphere** [comment]
Chrome and Outlook from my usage.

**Comment by stianhoiland** [comment]
This should be fixed in the upcoming v1.5 release. Let me know if the issue persists!
