### ISSUE TITLE
Can't switch to WhatsApp

### ISSUE THREAD

**Issue by dfelippa** [stianhoiland/cmdtab#7]
Thank you for this great app!

Can't alt+tab to whats app desktop app. It does not show on the list.

Equally "system informer" app, an utility like task manager does not show. 

Bellow a screen shot with whatsapp details, produced by system informar

![image](https://github.com/user-attachments/assets/b2920565-35c5-4b5a-b36a-10c8e681db33)

**Comment by stianhoiland** [comment]
Glad you like it!
That is definitely a bug. Thanks for supplying window information for WhatsApp.
It's not entirely clear to me what the cause of this is, although I do see in that list [a window class that is filtered out by cmdtab](https://github.com/stianhoiland/cmdtab/blob/746c41226cdd820c26eadf00eb86b45896dc1dcd/src/cmdtab.c#L468), in case you want to poke around and experiment with the code yourself before I eventually land on a fix.

**Comment by stianhoiland** [comment]
I never concretely investigated this issue with the WhatsApp application. The upcoming v1.5 is basically a rewrite with many issues resolved. If you end up downloading v1.5, let me know if this issue persists or not.
